server:
  port: 8083

spring:
  application:
    name: job-service

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-polished-fog-amshlcjk-pooler.c-5.us-east-1.aws.neon.tech:5432/neondb?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:neondb_owner}
    password: ${SPRING_DATASOURCE_PASSWORD:npg_3WGAnNgYMzw0}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

services:
  contract: ${CONTRACT_SERVICE_URL:http://contract-service}
  notification: ${NOTIFICATION_SERVICE_URL:http://notification-service}
  auth: ${AUTH_SERVICE_URL:http://auth-service}

# Notification service URL — used for sending emails


management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    com.freelancer.job: DEBUG